package research.v1;

import io.grpc.Context;
import io.grpc.Contexts;
import io.grpc.Metadata;
import io.grpc.ServerCall;
import io.grpc.ServerCallHandler;
import io.grpc.ServerInterceptor;

// Auto-generated by langgraph_to_proto.py
public class AgentIdInterceptor implements ServerInterceptor {

    public static final Metadata.Key<String> AGENT_ID_META =
            Metadata.Key.of("agent-id", Metadata.ASCII_STRING_MARSHALLER);

    public static final Metadata.Key<String> SERVER_NAME_META =
            Metadata.Key.of("server-name", Metadata.ASCII_STRING_MARSHALLER);

    public static final Context.Key<String> AGENT_ID =
            Context.key("agent-id");

    public static final Context.Key<String> SERVER_NAME =
            Context.key("server-name");

    @Override
    public <Req, Resp> ServerCall.Listener<Req> interceptCall(
            ServerCall<Req, Resp> call, Metadata headers, ServerCallHandler<Req, Resp> next) {
        String agentId = headers.get(AGENT_ID_META);
        String serverName = headers.get(SERVER_NAME_META);
        Context ctx = Context.current()
                .withValue(AGENT_ID, agentId != null ? agentId : "unknown")
                .withValue(SERVER_NAME, serverName != null ? serverName : "unknown");
        return Contexts.interceptCall(ctx, call, headers, next);
    }
}
