package research.v1;

import java.util.List;

// Auto-generated by langgraph_to_proto.py
public class AgentState {

    // The research task to complete
    private String task = "";

    // Results from the research agent
    private String research_results = "";

    // Files written by the writer agent
    private java.util.List<String> written_files = new java.util.ArrayList<>();

    // Next node to route to
    private String next = "";

    // Conversation history
    private java.util.List<String> chat_history = new java.util.ArrayList<>();

    public String getTask() { return task; }
    public void setTask(String v) { this.task = v; }

    public String getResearchResults() { return research_results; }
    public void setResearchResults(String v) { this.research_results = v; }

    public java.util.List<String> getWrittenFiles() { return written_files; }
    public void setWrittenFiles(java.util.List<String> v) { this.written_files = v; }

    public String getNext() { return next; }
    public void setNext(String v) { this.next = v; }

    public java.util.List<String> getChatHistory() { return chat_history; }
    public void setChatHistory(java.util.List<String> v) { this.chat_history = v; }
}
