package research.v1;

import io.grpc.Server;
import io.grpc.ServerBuilder;
import java.nio.file.Path;

// Auto-generated by langgraph_to_proto.py
public class FilesystemServerMain {
    public static final int PORT = 50052;

    public static void main(String[] args) throws Exception {
        Path outputDir = Path.of(System.getProperty("user.dir"), "output");
        outputDir.toFile().mkdirs();
        Server server = ServerBuilder.forPort(PORT)
                .addService(new FilesystemMCPServerImpl(outputDir))
                .intercept(new AgentIdInterceptor())
                .build()
                .start();
        System.out.println("filesystem MCP server listening on port " + PORT + " (output: " + outputDir + ")");
        server.awaitTermination();
    }
}
