package research.v1;

// Auto-generated by langgraph_to_proto.py — Agent: multi-research-agent
// Graph topology:
//   supervisor -> research_agent [next == 'research']
//   supervisor -> writer_agent [next == 'writer']
//   supervisor -> __end__ [next == 'FINISH']
//   research_agent -> supervisor
//   writer_agent -> supervisor
public class GraphRunner {

    private final SupervisorNode supervisorNode;
    private final ResearchAgentNode research_agentNode;
    private final WriterAgentNode writer_agentNode;

    public GraphRunner() {
        this.supervisorNode = new SupervisorNode();
        this.research_agentNode = new ResearchAgentNode();
        this.writer_agentNode = new WriterAgentNode();
    }

    public GraphRunner(SupervisorNode supervisorNode, ResearchAgentNode research_agentNode, WriterAgentNode writer_agentNode) {
        this.supervisorNode = supervisorNode;
        this.research_agentNode = research_agentNode;
        this.writer_agentNode = writer_agentNode;
    }

    public AgentState run(AgentState initialState) {
        AgentState state = initialState;
        String current = "supervisor";
        int maxSteps = 20;
        for (int step = 0; step < maxSteps; step++) {
            if (current.equals("__end__")) break;
            switch (current) {
case "supervisor":
    state = supervisorNode.run(state);
    current = route(state);
    if (!current.equals("__end__")) {
        MCPLogger.agentToAgent("supervisor", current, "Dispatch", "");
    } else {
        MCPLogger.agentToAgent("supervisor", "supervisor", "Complete", "");
    }
    break;
case "research_agent":
    state = research_agentNode.run(state);
    MCPLogger.agentToAgent("research_agent", "supervisor", "Complete", "");
    current = "supervisor";
    break;
case "writer_agent":
    state = writer_agentNode.run(state);
    MCPLogger.agentToAgent("writer_agent", "supervisor", "Complete", "");
    current = "supervisor";
    break;
                default:
                    System.err.println("Unknown node: " + current);
                    return state;
            }
        }
        return state;
    }

    private String route(AgentState state) {
        String n = state.getNext();
        if (n.equals("FINISH")) {
            return "__end__";
        }
        return n + "_agent";
    }

    public static void main(String[] args) {
        AgentState state = new AgentState();
        state.setTask(args.length > 0 ? args[0]
                : "Research the Python programming language and write a summary report");
        AgentState result = new GraphRunner().run(state);
        System.out.println("Files written: " + result.getWrittenFiles());
    }
}
