package research.v1;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.time.Instant;

// Auto-generated by langgraph_to_proto.py
public class MCPLogger {

    private static final Path MCP_LOG = Path.of(System.getProperty("user.dir"), "output", "message.log");
    private static final Object LOCK = new Object();
    private static volatile boolean enabled = true;

    private final String peerName;

    public MCPLogger(String peerName) {
        this.peerName = peerName;
    }

    public static void setEnabled(boolean value) {
        enabled = value;
    }

    public static void beginRun(String label) {
        synchronized (LOCK) {
            try {
                Files.createDirectories(MCP_LOG.getParent());
                String banner = String.format("%n### RUN START: %s [%s] ###%n", label, Instant.now());
                Files.writeString(MCP_LOG, banner, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
            } catch (IOException ignored) {}
        }
    }

    public static void agentToAgent(String source, String target, String action, String detail) {
        write(mapAgent(source), mapAgent(target), action, detail);
    }

    public void agentToLlm(String agent, String detail) {
        write(mapAgent(agent), "LLM", "Prompt", detail);
    }

    public void llmToAgent(String agent, String detail) {
        write("LLM", mapAgent(agent), "Result", detail);
    }

    public void toolToAgentSampling(String agent, String detail) {
        toolToAgentSampling(agent, peerName, detail);
    }

    public void agentToToolSampling(String agent, String detail) {
        agentToToolSampling(agent, peerName, detail);
    }

    public void toolToAgentSampling(String agent, String peer, String detail) {
        write(mapPeer(peer), mapAgent(agent), "Sampling", detail);
    }

    public void agentToToolSampling(String agent, String peer, String detail) {
        write(mapAgent(agent), mapPeer(peer), "SamplingResult", detail);
    }

    public void agentToTool(String agent, String method, String detail) {
        write(mapAgent(agent), mapPeer(peerName), method + "Request", detail);
    }

    public void toolToAgent(String agent, String method, String detail) {
        write(mapPeer(peerName), mapAgent(agent), method + "Response", detail);
    }

    private static String mapAgent(String agent) {
        if (agent == null) return "AGENT:unknown";
        return switch (agent) {
            case "supervisor", "orchestrator" -> "AGENT:orchestrator";
            case "research_agent", "searcher" -> "AGENT:searcher";
            case "writer_agent", "writer" -> "AGENT:writer";
            case "integration-test-agent", "test-client" -> "AGENT:test-client";
            default -> "AGENT:" + agent;
        };
    }

    private String mapPeer(String peer) {
        return switch (peer) {
            case "web-search-mcp-server", "web_search" -> "TOOL:web_search";
            case "filesystem-mcp-server", "filesystem" -> "TOOL:filesystem";
            case "sampling-service", "llm" -> "LLM";
            default -> peer;
        };
    }

    private static void write(String source, String target, String action, String detail) {
        if (!enabled) return;
        String ts = Instant.ofEpochMilli(System.currentTimeMillis()).toString();
        String entry = String.format("%-24s %-20s %-20s %-14s%n",
                ts, source, target, action);
        synchronized (LOCK) {
            try {
                Files.createDirectories(MCP_LOG.getParent());
                Files.writeString(MCP_LOG, entry, StandardOpenOption.CREATE, StandardOpenOption.APPEND);
            } catch (IOException ignored) {}
        }
    }

    public void log(String msg) {
        System.out.printf("[%s] [%s] %s%n", Instant.now(), peerName, msg);
        System.out.flush();
    }
}
