package research.v1;

import io.grpc.stub.StreamObserver;

// Auto-generated by langgraph_to_proto.py
public class OllamaMCPClientImpl extends MCPClientServiceGrpc.MCPClientServiceImplBase {

    @Override
    public void createMessage(Mcp.CreateMessageRequest req, StreamObserver<Mcp.CreateMessageResponse> out) {
        try {
            String userText = req.getMessagesCount() > 0
                    ? req.getMessages(0).getContent().getText().getText() : "";
            String response = OllamaClient.call(
                    req.getSystemPrompt(),
                    userText,
                    req.getMaxTokens() > 0 ? req.getMaxTokens() : 4096);
            out.onNext(Mcp.CreateMessageResponse.newBuilder()
                    .setRole(Mcp.PromptMessageRole.PROMPT_MESSAGE_ROLE_ASSISTANT)
                    .setContent(Mcp.Content.newBuilder()
                            .setText(Mcp.TextContent.newBuilder().setText(response)))
                    .setModel("qwen2.5:14b")
                    .setStopReason(Mcp.StopReason.STOP_REASON_END_TURN)
                    .build());
            out.onCompleted();
        } catch (Exception e) {
            out.onError(io.grpc.Status.INTERNAL
                    .withDescription("llama-server call failed: " + e.getMessage())
                    .asRuntimeException());
        }
    }

    @Override
    public void listRoots(Mcp.ListRootsRequest req, StreamObserver<Mcp.ListRootsResponse> out) {
        out.onNext(Mcp.ListRootsResponse.newBuilder().build());
        out.onCompleted();
    }
}
