package research.v1;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

// Auto-generated by langgraph_to_proto.py
public class OllamaClient {

    private static final String URL   = "http://localhost:11435/v1/chat/completions";
    static final String MODEL = "qwen2.5:14b";
    private static final HttpClient HTTP = HttpClient.newBuilder()
            .connectTimeout(Duration.ofSeconds(10))
            .build();

    public static String call(String systemPrompt, String userMessage, int maxTokens) {
        // Allow stub via system property for testing without LLM server
        String stub = System.getProperty("ollama.stub");
        if (stub != null && !stub.isEmpty()) {
            return stub;
        }
        int maxAttempts = 2;
        long delayMs = 500;
        Exception lastException = null;

        for (int attempt = 1; attempt <= maxAttempts; attempt++) {
            try {
                JsonObject body = new JsonObject();
                body.addProperty("model", MODEL);
                body.addProperty("max_tokens", maxTokens);

                JsonArray messages = new JsonArray();
                if (systemPrompt != null && !systemPrompt.isEmpty()) {
                    JsonObject sys = new JsonObject();
                    sys.addProperty("role", "system");
                    sys.addProperty("content", systemPrompt);
                    messages.add(sys);
                }
                JsonObject user = new JsonObject();
                user.addProperty("role", "user");
                user.addProperty("content", userMessage);
                messages.add(user);
                body.add("messages", messages);

                HttpRequest req = HttpRequest.newBuilder()
                        .uri(URI.create(URL))
                        .header("Content-Type", "application/json")
                        .POST(HttpRequest.BodyPublishers.ofString(body.toString()))
                        .build();

                HttpResponse<String> resp = HTTP.send(req, HttpResponse.BodyHandlers.ofString());
                if (resp.statusCode() != 200) {
                    throw new RuntimeException("Ollama returned non-200 status code: " + resp.statusCode() + " body: " + resp.body());
                }

                return JsonParser.parseString(resp.body())
                        .getAsJsonObject()
                        .getAsJsonArray("choices")
                        .get(0).getAsJsonObject()
                        .getAsJsonObject("message")
                        .get("content").getAsString();
            } catch (Exception e) {
                System.err.println("[OllamaClient] Attempt " + attempt + " failed: " + e.getMessage());
                lastException = e;
                if (attempt < maxAttempts) {
                    long sleepTime = delayMs * attempt;
                    System.out.println("[OllamaClient] Sleeping " + sleepTime + "ms before retrying...");
                    try {
                        Thread.sleep(sleepTime);
                    } catch (InterruptedException ie) {
                        Thread.currentThread().interrupt();
                        throw new RuntimeException("Ollama client call interrupted", ie);
                    }
                }
            }
        }
        throw new RuntimeException("llama-server call failed after " + maxAttempts + " attempts: " + (lastException != null ? lastException.getMessage() : "unknown error"), lastException);
    }
}
