package research.v1;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import io.grpc.ManagedChannelBuilder;
import io.grpc.Server;
import io.grpc.ServerBuilder;
import io.grpc.stub.StreamObserver;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.http.HttpRequest.BodyPublishers;
import java.net.http.HttpResponse.BodyHandlers;
import java.util.Arrays;
import java.util.concurrent.TimeUnit;

// Auto-generated by langgraph_to_proto.py
// Node: research_agent — Chooses a search query via LLM sampling, then calls the web-search MCP server.
public class ResearchAgentNode extends BaseAgentNode {

    private MCPServerServiceGrpc.MCPServerServiceBlockingStub web_search_stub;
    private MCPClientServiceGrpc.MCPClientServiceBlockingStub samplingStub;
    private static final String WEB_SEARCH_HTTP_URL = "http://localhost:50061/mcp";
    private boolean web_search_httpAvailable = false;
    private static final HttpClient httpClient = HttpClient.newHttpClient();

    public ResearchAgentNode() {
        super("searcher");
        web_search_httpAvailable = initHttpServer(WEB_SEARCH_HTTP_URL, "searcher");
        if (!web_search_httpAvailable) {
            io.grpc.Metadata headers_web_search_stub = new io.grpc.Metadata();
            headers_web_search_stub.put(AgentIdInterceptor.AGENT_ID_META, "searcher");
            web_search_stub = MCPServerServiceGrpc.newBlockingStub(
                    ManagedChannelBuilder.forAddress("localhost", 50051).usePlaintext().build())
                    .withInterceptors(io.grpc.stub.MetadataUtils.newAttachHeadersInterceptor(headers_web_search_stub));
            web_search_stub.initialize(Mcp.InitializeRequest.newBuilder()
                    .setProtocolVersion("2025-11-25")
                    .setClientInfo(Mcp.ClientInfo.newBuilder()
                            .setName("searcher")
                            .setVersion("1.0")
                            .setCallbackAddress("localhost:50055"))
                    .setCapabilities(Mcp.ClientCapabilities.newBuilder()
                            .setSampling(Mcp.SamplingCapability.newBuilder().build())
                            .build())
                    .build());
            web_search_stub.notify(Mcp.NotifyRequest.newBuilder()
                    .setInitialized(Mcp.InitializedNotification.newBuilder().build())                    .build());
        }
        io.grpc.Metadata headers_sampling = new io.grpc.Metadata();
        headers_sampling.put(AgentIdInterceptor.AGENT_ID_META, "searcher");
        headers_sampling.put(AgentIdInterceptor.SERVER_NAME_META, "searcher");
        samplingStub = MCPClientServiceGrpc.newBlockingStub(
                ManagedChannelBuilder.forAddress("localhost", 50055).usePlaintext().build())
                .withInterceptors(io.grpc.stub.MetadataUtils.newAttachHeadersInterceptor(headers_sampling));
    }

private String sample(String system, String user, int maxTokens) {
    log.agentToLlm("searcher", "\"" + system + "\"");
    String result = samplingStub.createMessage(Mcp.CreateMessageRequest.newBuilder()
            .setSystemPrompt(system)
            .addMessages(Mcp.SamplingMessage.newBuilder()
                    .setRole(Mcp.PromptMessageRole.PROMPT_MESSAGE_ROLE_USER)
                    .setContent(Mcp.Content.newBuilder()
                            .setText(Mcp.TextContent.newBuilder().setText(user))))
            .setMaxTokens(maxTokens)
            .build())
            .getContent().getText().getText().trim();
    log.llmToAgent("searcher", "\"" + result.replace("\n", " ").substring(0, Math.min(120, result.length())) + "\"");
    return result;
}

private boolean initHttpServer(String url, String agentName) {
    try {
        JsonObject ping = new JsonObject();
        ping.addProperty("jsonrpc", "2.0");
        ping.addProperty("method", "ping");
        ping.addProperty("id", 0);
        ping.add("params", new JsonObject());
        HttpRequest req = HttpRequest.newBuilder()
                .uri(URI.create(url))
                .header("Content-Type", "application/json")
                .header("Accept", "application/json")
                .header("MCP-Protocol-Version", "2025-11-25")
                .POST(BodyPublishers.ofString(ping.toString()))
                .build();
        HttpResponse<String> resp = httpClient.send(req, BodyHandlers.ofString());
        if (resp.statusCode() != 200) return false;
        JsonObject clientInfo = new JsonObject();
        clientInfo.addProperty("name", agentName);
        clientInfo.addProperty("version", "1.0");
        JsonObject caps = new JsonObject();
        caps.add("sampling", new JsonObject());
        JsonObject initParams = new JsonObject();
        initParams.addProperty("protocolVersion", "2025-11-25");
        initParams.add("clientInfo", clientInfo);
        initParams.add("capabilities", caps);
        jsonRpcRequest(url, 1, "initialize", initParams);
        jsonRpcRequest(url, 0, "notifications/initialized", null);
        return true;
    } catch (Exception e) {
        return false;
    }
}

private JsonObject jsonRpcRequest(String url, int id, String method, JsonObject params) throws Exception {
    JsonObject envelope = new JsonObject();
    envelope.addProperty("jsonrpc", "2.0");
    envelope.addProperty("method", method);
    envelope.addProperty("id", id);
    if (params != null) {
        envelope.add("params", params);
    }
    HttpRequest req = HttpRequest.newBuilder()
            .uri(URI.create(url))
            .header("Content-Type", "application/json")
            .header("Accept", "application/json")
            .header("MCP-Protocol-Version", "2025-11-25")
            .POST(BodyPublishers.ofString(envelope.toString()))
            .build();
    HttpResponse<String> resp = httpClient.send(req, BodyHandlers.ofString());
    return JsonParser.parseString(resp.body()).getAsJsonObject();
}

    // Translated from Python: research_agent_node
    public AgentState run(AgentState state) {
        String query = sample("Reply with a simple search query or topic keyword to look up (e.g. 'Python programming language'). No punctuation or explanation.", state.getTask(), 4096).trim().trim();
        query = String.join(" ", java.util.Arrays.stream(query.split("\\s+")).filter(w -> w.matches("[a-zA-Z0-9]+") || w.length() > 1).map(w -> w).collect(java.util.stream.Collectors.joining(" ")));
        String result = web_search_and_analyze(query);
        String thought = "Research Agent: Searched for '" + query + "' and retrieved results.";
        state.getChatHistory().add(thought);
        state.setResearchResults(result);
        return state;
    }

String web_search_and_analyze(String query) {
    if (web_search_httpAvailable) {
        try {
            JsonObject args = new JsonObject();
            args.addProperty("query", query);
            JsonObject callParams = new JsonObject();
            callParams.addProperty("name", "web_search");
            callParams.add("arguments", args);
            JsonObject resp = jsonRpcRequest(WEB_SEARCH_HTTP_URL, 2, "tools/call", callParams);
            return resp.getAsJsonObject("result").getAsJsonArray("content")
                    .get(0).getAsJsonObject().get("text").getAsString();
        } catch (Exception e) {
            // fall through to gRPC
        }
    }
    Mcp.CallToolResponse resp = web_search_stub.callTool(
            Mcp.CallToolRequest.newBuilder()
                    .setName("web_search")
                    .setArguments(com.google.protobuf.Struct.newBuilder()
                            .putFields("query", com.google.protobuf.Value.newBuilder().setStringValue(query).build())
                            .build())
                    .build());
    return resp.getContent(0).getText().getText();
}

    public static void main(String[] args) throws Exception {
        Server server = ServerBuilder.forPort(50055)
                .addService(new ResearchAgentNode())
                .intercept(new AgentIdInterceptor())
                .build().start();
        System.out.println("ResearchAgentNode listening on port " + 50055);
        server.awaitTermination();
    }
}
