package research.v1;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import io.grpc.ManagedChannelBuilder;
import io.grpc.Server;
import io.grpc.ServerBuilder;
import io.grpc.stub.StreamObserver;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.http.HttpRequest.BodyPublishers;
import java.net.http.HttpResponse.BodyHandlers;
import java.util.Arrays;
import java.util.concurrent.TimeUnit;

// Auto-generated by langgraph_to_proto.py
// Node: supervisor — Routes tasks to specialized agents based on state. Uses LLM sampling to reason about next step.
public class SupervisorNode extends BaseAgentNode {

    private MCPClientServiceGrpc.MCPClientServiceBlockingStub samplingStub;
    private static final HttpClient httpClient = HttpClient.newHttpClient();

    public SupervisorNode() {
        super("orchestrator");
        io.grpc.Metadata headers_sampling = new io.grpc.Metadata();
        headers_sampling.put(AgentIdInterceptor.AGENT_ID_META, "orchestrator");
        headers_sampling.put(AgentIdInterceptor.SERVER_NAME_META, "orchestrator");
        samplingStub = MCPClientServiceGrpc.newBlockingStub(
                ManagedChannelBuilder.forAddress("localhost", 50053).usePlaintext().build())
                .withInterceptors(io.grpc.stub.MetadataUtils.newAttachHeadersInterceptor(headers_sampling));
    }

private String sample(String system, String user, int maxTokens) {
    log.agentToLlm("orchestrator", "\"" + system + "\"");
    String result = samplingStub.createMessage(Mcp.CreateMessageRequest.newBuilder()
            .setSystemPrompt(system)
            .addMessages(Mcp.SamplingMessage.newBuilder()
                    .setRole(Mcp.PromptMessageRole.PROMPT_MESSAGE_ROLE_USER)
                    .setContent(Mcp.Content.newBuilder()
                            .setText(Mcp.TextContent.newBuilder().setText(user))))
            .setMaxTokens(maxTokens)
            .build())
            .getContent().getText().getText().trim();
    log.llmToAgent("orchestrator", "\"" + result.replace("\n", " ").substring(0, Math.min(120, result.length())) + "\"");
    return result;
}

private boolean initHttpServer(String url, String agentName) {
    try {
        JsonObject ping = new JsonObject();
        ping.addProperty("jsonrpc", "2.0");
        ping.addProperty("method", "ping");
        ping.addProperty("id", 0);
        ping.add("params", new JsonObject());
        HttpRequest req = HttpRequest.newBuilder()
                .uri(URI.create(url))
                .header("Content-Type", "application/json")
                .header("Accept", "application/json")
                .header("MCP-Protocol-Version", "2025-11-25")
                .POST(BodyPublishers.ofString(ping.toString()))
                .build();
        HttpResponse<String> resp = httpClient.send(req, BodyHandlers.ofString());
        if (resp.statusCode() != 200) return false;
        JsonObject clientInfo = new JsonObject();
        clientInfo.addProperty("name", agentName);
        clientInfo.addProperty("version", "1.0");
        JsonObject caps = new JsonObject();
        caps.add("sampling", new JsonObject());
        JsonObject initParams = new JsonObject();
        initParams.addProperty("protocolVersion", "2025-11-25");
        initParams.add("clientInfo", clientInfo);
        initParams.add("capabilities", caps);
        jsonRpcRequest(url, 1, "initialize", initParams);
        jsonRpcRequest(url, 0, "notifications/initialized", null);
        return true;
    } catch (Exception e) {
        return false;
    }
}

private JsonObject jsonRpcRequest(String url, int id, String method, JsonObject params) throws Exception {
    JsonObject envelope = new JsonObject();
    envelope.addProperty("jsonrpc", "2.0");
    envelope.addProperty("method", method);
    envelope.addProperty("id", id);
    if (params != null) {
        envelope.add("params", params);
    }
    HttpRequest req = HttpRequest.newBuilder()
            .uri(URI.create(url))
            .header("Content-Type", "application/json")
            .header("Accept", "application/json")
            .header("MCP-Protocol-Version", "2025-11-25")
            .POST(BodyPublishers.ofString(envelope.toString()))
            .build();
    HttpResponse<String> resp = httpClient.send(req, BodyHandlers.ofString());
    return JsonParser.parseString(resp.body()).getAsJsonObject();
}

    // Translated from Python: supervisor_node
    public AgentState run(AgentState state) {
        boolean research_done = (state.getResearchResults() != null && !state.getResearchResults().isEmpty());
        boolean files_written = (state.getWrittenFiles() != null && !state.getWrittenFiles().isEmpty());
        String decision = (!research_done ? "research" : (!files_written ? "writer" : "FINISH"));
        String reasoning = null;
        if (!decision.equals("FINISH")) {
            reasoning = sample("Reply with ONE word: research, writer, or FINISH.", "Task: " + state.getTask() + "\nResearch done: " + (research_done ? "yes" : "no") + "\nFiles written: " + (files_written ? state.getWrittenFiles() : "none"), 16).trim();
        } else {
            reasoning = "All done. Files written: " + state.getWrittenFiles();
        }
        state.getChatHistory().add(reasoning);
        state.setNext(decision);
        return state;
    }



    public static void main(String[] args) throws Exception {
        Server server = ServerBuilder.forPort(50053)
                .addService(new SupervisorNode())
                .intercept(new AgentIdInterceptor())
                .build().start();
        System.out.println("SupervisorNode listening on port " + 50053);
        server.awaitTermination();
    }
}
