package research.v1;

import io.grpc.Server;
import io.grpc.ServerBuilder;

// Auto-generated by langgraph_to_proto.py
public class WebSearchServerMain {
    public static final int PORT = 50051;

    public static void main(String[] args) throws Exception {
        Server server = ServerBuilder.forPort(PORT)
                .addService(new WebSearchMCPServerImpl())
                .intercept(new AgentIdInterceptor())
                .build()
                .start();
        System.out.println("web-search MCP server listening on port " + PORT);
        server.awaitTermination();
    }
}
