package research.v1;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import io.grpc.ManagedChannelBuilder;
import io.grpc.Server;
import io.grpc.ServerBuilder;
import io.grpc.stub.StreamObserver;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.http.HttpRequest.BodyPublishers;
import java.net.http.HttpResponse.BodyHandlers;
import java.util.Arrays;
import java.util.concurrent.TimeUnit;

// Auto-generated by langgraph_to_proto.py
// Node: writer_agent — Drafts content via LLM sampling, then calls the filesystem MCP server to write it.
public class WriterAgentNode extends BaseAgentNode {

    private MCPServerServiceGrpc.MCPServerServiceBlockingStub filesystem_stub;
    private MCPClientServiceGrpc.MCPClientServiceBlockingStub samplingStub;
    private static final String FILESYSTEM_HTTP_URL = "http://localhost:50062/mcp";
    private boolean filesystem_httpAvailable = false;
    private static final HttpClient httpClient = HttpClient.newHttpClient();

    public WriterAgentNode() {
        super("writer");
        filesystem_httpAvailable = initHttpServer(FILESYSTEM_HTTP_URL, "writer");
        if (!filesystem_httpAvailable) {
            io.grpc.Metadata headers_filesystem_stub = new io.grpc.Metadata();
            headers_filesystem_stub.put(AgentIdInterceptor.AGENT_ID_META, "writer");
            filesystem_stub = MCPServerServiceGrpc.newBlockingStub(
                    ManagedChannelBuilder.forAddress("localhost", 50052).usePlaintext().build())
                    .withInterceptors(io.grpc.stub.MetadataUtils.newAttachHeadersInterceptor(headers_filesystem_stub));
            filesystem_stub.initialize(Mcp.InitializeRequest.newBuilder()
                    .setProtocolVersion("2025-11-25")
                    .setClientInfo(Mcp.ClientInfo.newBuilder()
                            .setName("writer")
                            .setVersion("1.0")
                            .setCallbackAddress("localhost:50056"))
                    .setCapabilities(Mcp.ClientCapabilities.newBuilder()
                            .setSampling(Mcp.SamplingCapability.newBuilder().build())
                            .build())
                    .build());
            filesystem_stub.notify(Mcp.NotifyRequest.newBuilder()
                    .setInitialized(Mcp.InitializedNotification.newBuilder().build())                    .build());
        }
        io.grpc.Metadata headers_sampling = new io.grpc.Metadata();
        headers_sampling.put(AgentIdInterceptor.AGENT_ID_META, "writer");
        headers_sampling.put(AgentIdInterceptor.SERVER_NAME_META, "writer");
        samplingStub = MCPClientServiceGrpc.newBlockingStub(
                ManagedChannelBuilder.forAddress("localhost", 50056).usePlaintext().build())
                .withInterceptors(io.grpc.stub.MetadataUtils.newAttachHeadersInterceptor(headers_sampling));
    }

private String sample(String system, String user, int maxTokens) {
    log.agentToLlm("writer", "\"" + system + "\"");
    String result = samplingStub.createMessage(Mcp.CreateMessageRequest.newBuilder()
            .setSystemPrompt(system)
            .addMessages(Mcp.SamplingMessage.newBuilder()
                    .setRole(Mcp.PromptMessageRole.PROMPT_MESSAGE_ROLE_USER)
                    .setContent(Mcp.Content.newBuilder()
                            .setText(Mcp.TextContent.newBuilder().setText(user))))
            .setMaxTokens(maxTokens)
            .build())
            .getContent().getText().getText().trim();
    log.llmToAgent("writer", "\"" + result.replace("\n", " ").substring(0, Math.min(120, result.length())) + "\"");
    return result;
}

private boolean initHttpServer(String url, String agentName) {
    try {
        JsonObject ping = new JsonObject();
        ping.addProperty("jsonrpc", "2.0");
        ping.addProperty("method", "ping");
        ping.addProperty("id", 0);
        ping.add("params", new JsonObject());
        HttpRequest req = HttpRequest.newBuilder()
                .uri(URI.create(url))
                .header("Content-Type", "application/json")
                .header("Accept", "application/json")
                .header("MCP-Protocol-Version", "2025-11-25")
                .POST(BodyPublishers.ofString(ping.toString()))
                .build();
        HttpResponse<String> resp = httpClient.send(req, BodyHandlers.ofString());
        if (resp.statusCode() != 200) return false;
        JsonObject clientInfo = new JsonObject();
        clientInfo.addProperty("name", agentName);
        clientInfo.addProperty("version", "1.0");
        JsonObject caps = new JsonObject();
        caps.add("sampling", new JsonObject());
        JsonObject initParams = new JsonObject();
        initParams.addProperty("protocolVersion", "2025-11-25");
        initParams.add("clientInfo", clientInfo);
        initParams.add("capabilities", caps);
        jsonRpcRequest(url, 1, "initialize", initParams);
        jsonRpcRequest(url, 0, "notifications/initialized", null);
        return true;
    } catch (Exception e) {
        return false;
    }
}

private JsonObject jsonRpcRequest(String url, int id, String method, JsonObject params) throws Exception {
    JsonObject envelope = new JsonObject();
    envelope.addProperty("jsonrpc", "2.0");
    envelope.addProperty("method", method);
    envelope.addProperty("id", id);
    if (params != null) {
        envelope.add("params", params);
    }
    HttpRequest req = HttpRequest.newBuilder()
            .uri(URI.create(url))
            .header("Content-Type", "application/json")
            .header("Accept", "application/json")
            .header("MCP-Protocol-Version", "2025-11-25")
            .POST(BodyPublishers.ofString(envelope.toString()))
            .build();
    HttpResponse<String> resp = httpClient.send(req, BodyHandlers.ofString());
    return JsonParser.parseString(resp.body()).getAsJsonObject();
}

    // Translated from Python: writer_agent_node
    public AgentState run(AgentState state) {
        String draft = sample("You are a technical writer. Write a 3-5 sentence summary of the research. Be factual, no introductions.", "Task: " + state.getTask() + "\nResearch: " + state.getResearchResults(), 2048);
        String filename = "research_report.txt";
        String result = format_and_write(filename, draft);
        String thought = "Writer Agent: Wrote report to '" + filename + "'.";
        state.getChatHistory().add(thought);
        state.setWrittenFiles(java.util.Arrays.asList(filename));
        return state;
    }

String format_and_write(String filename, String content) {
    if (filesystem_httpAvailable) {
        try {
            JsonObject args = new JsonObject();
            args.addProperty("name", filename);
        args.addProperty("content", content);
            JsonObject callParams = new JsonObject();
            callParams.addProperty("name", "write_file");
            callParams.add("arguments", args);
            JsonObject resp = jsonRpcRequest(FILESYSTEM_HTTP_URL, 2, "tools/call", callParams);
            return resp.getAsJsonObject("result").getAsJsonArray("content")
                    .get(0).getAsJsonObject().get("text").getAsString();
        } catch (Exception e) {
            // fall through to gRPC
        }
    }
    Mcp.CallToolResponse resp = filesystem_stub.callTool(
            Mcp.CallToolRequest.newBuilder()
                    .setName("write_file")
                    .setArguments(com.google.protobuf.Struct.newBuilder()
                            .putFields("name", com.google.protobuf.Value.newBuilder().setStringValue(filename).build())
                    .putFields("content", com.google.protobuf.Value.newBuilder().setStringValue(content).build())
                            .build())
                    .build());
    return resp.getContent(0).getText().getText();
}

    public static void main(String[] args) throws Exception {
        Server server = ServerBuilder.forPort(50056)
                .addService(new WriterAgentNode())
                .intercept(new AgentIdInterceptor())
                .build().start();
        System.out.println("WriterAgentNode listening on port " + 50056);
        server.awaitTermination();
    }
}
