package research.v1;

import com.google.protobuf.InvalidProtocolBufferException;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

// Auto-generated by langgraph_to_proto.py — agent: multi-research-agent
// Tools: web_search_and_analyze, format_and_write
public class McpProtoTest {

    private static void section(String title) { System.out.println("\n" + title); }
    private static void print(String l, Object v) { System.out.println("[" + l + "] " + v); }


    // -----------------------------------------------------------------------
    // Fixed protocol tests
    // -----------------------------------------------------------------------

    @Test
    public void promptMessageRole_values() throws Exception {
        section("TEST 1 of 9: PromptMessageRole — all enum values and wire numbers");
        for (Mcp.PromptMessageRole r : Mcp.PromptMessageRole.values()) {
            if (r == Mcp.PromptMessageRole.UNRECOGNIZED) continue;
            print("PromptMessageRole", r.name() + " = " + r.getNumber());
        }
        assertEquals(0, Mcp.PromptMessageRole.PROMPT_MESSAGE_ROLE_UNSPECIFIED.getNumber());
        assertEquals(1, Mcp.PromptMessageRole.PROMPT_MESSAGE_ROLE_USER.getNumber());
        assertEquals(2, Mcp.PromptMessageRole.PROMPT_MESSAGE_ROLE_ASSISTANT.getNumber());
    }

    @Test
    public void stopReason_values() throws Exception {
        section("TEST 2 of 9: StopReason — all enum values and wire numbers");
        for (Mcp.StopReason r : Mcp.StopReason.values()) {
            if (r == Mcp.StopReason.UNRECOGNIZED) continue;
            print("StopReason", r.name() + " = " + r.getNumber());
        }
        assertEquals(1, Mcp.StopReason.STOP_REASON_END_TURN.getNumber());
        assertEquals(2, Mcp.StopReason.STOP_REASON_MAX_TOKENS.getNumber());
        assertEquals(3, Mcp.StopReason.STOP_REASON_STOP_SEQUENCE.getNumber());
    }

    @Test
    public void content_textKind() throws Exception {
        section("TEST 3 of 9: Content oneof — TEXT variant carries the string");
        Mcp.Content c = Mcp.Content.newBuilder()
                .setText(Mcp.TextContent.newBuilder().setText("hello world"))
                .build();
        print("Content", c);
        assertEquals(Mcp.Content.KindCase.TEXT, c.getKindCase());
        assertEquals("hello world", c.getText().getText());
    }

    @Test
    public void initializeRequest_roundTrip() throws InvalidProtocolBufferException {
        section("TEST 4 of 9: InitializeRequest — protocol version + capabilities survive serialize/parse");
        Mcp.InitializeRequest req = Mcp.InitializeRequest.newBuilder()
                .setProtocolVersion("2025-11-25")
                .setClientInfo(Mcp.ClientInfo.newBuilder().setName("test-client").setVersion("1.0"))
                .setCapabilities(Mcp.ClientCapabilities.newBuilder()
                        .setSampling(Mcp.SamplingCapability.newBuilder().build()))
                .build();
        print("Original", req);
        Mcp.InitializeRequest parsed = Mcp.InitializeRequest.parseFrom(req.toByteArray());
        print("Parsed", parsed);
        print("Serialized size", req.toByteArray().length + " bytes");
        assertEquals("2025-11-25", parsed.getProtocolVersion());
        assertEquals("test-client", parsed.getClientInfo().getName());
        assertTrue(parsed.getCapabilities().hasSampling());
    }

    @Test
    public void createMessageRequest_roundTrip() throws InvalidProtocolBufferException {
        section("TEST 5 of 9: CreateMessageRequest — sampling request survives serialize/parse");
        Mcp.CreateMessageRequest req = Mcp.CreateMessageRequest.newBuilder()
                .addMessages(Mcp.SamplingMessage.newBuilder()
                        .setRole(Mcp.PromptMessageRole.PROMPT_MESSAGE_ROLE_USER)
                        .setContent(Mcp.Content.newBuilder()
                                .setText(Mcp.TextContent.newBuilder().setText("Hello"))))
                .setModelPreferences(Mcp.ModelPreferences.newBuilder()
                        .addHints(Mcp.ModelHint.newBuilder().setName("test-model")))
                .setMaxTokens(256)
                .build();
        print("Original", req);
        Mcp.CreateMessageRequest parsed = Mcp.CreateMessageRequest.parseFrom(req.toByteArray());
        print("Parsed", parsed);
        assertEquals(1, parsed.getMessagesCount());
        assertEquals("test-model", parsed.getModelPreferences().getHints(0).getName());
        assertEquals(256, parsed.getMaxTokens());
    }

    // -----------------------------------------------------------------------
    // Generated per-tool: input message round-trip
    // -----------------------------------------------------------------------

    @Test
    public void web_search_and_analyze_input_roundTrip() throws InvalidProtocolBufferException {
        section("TEST 6 of 9: WebSearchAndAnalyzeInput — Search the web via MCP server and synthesize key facts using LLM sampling. — round-trip serialize/parse");
        Mcp.WebSearchAndAnalyzeInput msg = Mcp.WebSearchAndAnalyzeInput.newBuilder()
                .setQuery("test_query")
                .build();
        print("Original", msg);
        Mcp.WebSearchAndAnalyzeInput parsed = Mcp.WebSearchAndAnalyzeInput.parseFrom(msg.toByteArray());
        print("Parsed", parsed);
        print("Serialized bytes", msg.toByteArray().length + " bytes");
        assertEquals("test_query", parsed.getQuery());
    }

    @Test
    public void format_and_write_input_roundTrip() throws InvalidProtocolBufferException {
        section("TEST 7 of 9: FormatAndWriteInput — Format content as a structured report using LLM sampling, then write via MCP filesystem server. — round-trip serialize/parse");
        Mcp.FormatAndWriteInput msg = Mcp.FormatAndWriteInput.newBuilder()
                .setFilename("test_filename")
                .setContent("test_content")
                .build();
        print("Original", msg);
        Mcp.FormatAndWriteInput parsed = Mcp.FormatAndWriteInput.parseFrom(msg.toByteArray());
        print("Parsed", parsed);
        print("Serialized bytes", msg.toByteArray().length + " bytes");
        assertEquals("test_filename", parsed.getFilename());
        assertEquals("test_content", parsed.getContent());
    }

    // -----------------------------------------------------------------------
    // Generated per-tool: CallToolRequest
    // -----------------------------------------------------------------------

    @Test
    public void callToolRequest_web_search_and_analyze() throws InvalidProtocolBufferException {
        section("TEST 8 of 9: CallToolRequest for 'web_search_and_analyze' — name and arguments serialize correctly");
        Mcp.CallToolRequest req = Mcp.CallToolRequest.newBuilder()
                .setName("web_search_and_analyze")
                .setArguments(com.google.protobuf.Struct.newBuilder()
                        .putFields("query", com.google.protobuf.Value.newBuilder().setStringValue("test_query").build())
                        .build())
                .build();
        print("CallToolRequest", req);
        Mcp.CallToolRequest parsed = Mcp.CallToolRequest.parseFrom(req.toByteArray());
        assertEquals("web_search_and_analyze", parsed.getName());
        print("Tool name", parsed.getName());
        print("Argument count", parsed.getArguments().getFieldsCount());
    }

    @Test
    public void callToolRequest_format_and_write() throws InvalidProtocolBufferException {
        section("TEST 9 of 9: CallToolRequest for 'format_and_write' — name and arguments serialize correctly");
        Mcp.CallToolRequest req = Mcp.CallToolRequest.newBuilder()
                .setName("format_and_write")
                .setArguments(com.google.protobuf.Struct.newBuilder()
                        .putFields("filename", com.google.protobuf.Value.newBuilder().setStringValue("test_filename").build())
                        .putFields("content", com.google.protobuf.Value.newBuilder().setStringValue("test_content").build())
                        .build())
                .build();
        print("CallToolRequest", req);
        Mcp.CallToolRequest parsed = Mcp.CallToolRequest.parseFrom(req.toByteArray());
        assertEquals("format_and_write", parsed.getName());
        print("Tool name", parsed.getName());
        print("Argument count", parsed.getArguments().getFieldsCount());
    }
}